In [24]:
# Import the below libraries:
"""For faster loading, consider importing the libraries in separate cells."""
# To create reproducible file paths
import os # To interact with the operating system
from pathlib import Path # To create Path objects
import pathlib # To access the object-oriented library for paths

# For unzipping folders
import time # To handle time-related tasks
import zipfile # To download and extract zip files

# For saving Python objects
import pickle # To pickle datasets that take long periods to process

# To use APIs
import requests # For sending API requests

# To work with different types of data
import geopandas as gpd # To make GeoDataFrames/work with vector data
from glob import glob # To combine data arrays
from math import floor, ceil # For dealing with integers
import numpy as np # To work with arrays
import openpyxl # To read XLSX files
import pandas as pd # To work with dataframes
import rasterio # For handling raster soil maps
import rioxarray as rxr # To work with raster data
import rioxarray.merge as rxrm # To merge raster data
from shapely.geometry import box # To create bounding boxes
from shapely.geometry import MultiPolygon, Polygon # To handle invalid geometries
import xarray as xr # To use xarray datasets

# For visualization and interactive plotting
import contextily as ctx # To restore geography to the base map
import holoviews as hv # To create interactive hvPlots
import hvplot.pandas # To enable hvPlot interactive plotting for Pandas dataframes
import hvplot.xarray # To enable hvPlot interactive plotting for xarray datasets
import matplotlib.gridspec as gridspec # To display the plot legends properly
import matplotlib.pyplot as plt # To import the Pyplot module
import pyproj # For converting axes ticks to degrees

In [2]:
# Create a designated folder for the stoichiometric nutrient data
"""Note: the precise destination of the repository folder will vary from individual to individual."""
stoichiometry_data_dir = os.path.join(
    pathlib.Path.home(),
    # In the earth-analytics data folder
    'earth-analytics',
    'data',
    # Specify the destination as inside the "PLANT-B-Stoichiometric-Nutrient-Cycle-Simulation" repository
    'PLANT-B-Stoichiometric-Nutrient-Cycle-Simulation',
    'stoichiometric_nutrient_cycle_simulation'
)

# Create the directory
os.makedirs(stoichiometry_data_dir, exist_ok=True)

In [3]:
# Create a directory to store the species stoichiometry data
species_stoichiometry_dir = os.path.join(stoichiometry_data_dir, 'species_stoichiometry_dir')
os.makedirs(species_stoichiometry_dir, exist_ok=True)

In [ ]:
# Create a directory to store the StoichLife data inside the species stoichiometry directory
StoichLife_dir = os.path.join(species_stoichiometry_dir, 'isopod_and_springtail_StoichLife_data')
os.makedirs(StoichLife_dir, exist_ok=True)

# Establish the URL to the XLSX file for the download
StoichLife_url = "https://datadryad.org/downloads/file_stream/3918707"

# Define the path to the XLSX file
StoichLife_path = os.path.join(StoichLife_dir, "datapaper_2025_02_11.xlsx")

"""Function code to successfully download the XLSX file is pending."""

'Function code to successfully download the XLSX file is pending.'

In [ ]:
# Save the "data" sheet of the XLSX file as a dataframe
"""The XLSX file also contains a "metadata" and "references" sheet. The "metadata" sheet details what the variables (ex. habitat) are
describing."""
StoichLife_df = pd.read_excel(StoichLife_path, sheet_name="data")

# Display the data
StoichLife_df

,data.source1,data.type,data.provider1,lat.dec,long.dec,location,habitat.gen,habitat,kingdom_init,phylum_init,...,taxa.np,taxa.mass.cn,taxa.mass.cp,taxa.mass.np,body.weight.gr,temperature,radiation,N,P_ter,P_mar
0,unpublished - Alfaro,template,Alfaro,-20.105400,-67.330000,-20.1054 -67.33,terrestrial,terrestrial,Animalia,Arthropoda,...,149.717942,NaN,NaN,67.705882,0.000628,7.46,6.20,60.439308,43.495975,0.782
1,unpublished - Alfaro,template,Alfaro,-20.105400,-67.330000,-20.1054 -67.33,terrestrial,terrestrial,Animalia,Arthropoda,...,54.923883,4.548422,112.972973,24.837838,0.000431,7.46,6.20,60.439308,43.495975,0.782
2,Benstead et al. 2010,paper,NaN,18.159600,-65.982700,18.1596 -65.9827,aquatic,freshwater,Animalia,Arthropoda,...,27.617712,4.126065,51.531915,12.489362,0.199900,26.41,5.78,104.139830,18.790420,0.067
3,Benstead et al. 2010,paper,NaN,18.159600,-65.982700,18.1596 -65.9827,aquatic,freshwater,Animalia,Arthropoda,...,23.249069,4.092496,43.027523,10.513761,0.097500,26.41,5.78,104.139830,18.790420,0.067
4,Benstead et al. 2010,paper,NaN,18.316940,-65.746670,18.31694 -65.74667,aquatic,freshwater,Animalia,Arthropoda,...,25.642952,3.636076,42.165138,11.596330,0.109600,26.41,5.78,104.139830,21.631483,0.067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28044,unpublished - Roussel,template,Roussel,-49.275057,70.114103,-49.275057 70.114103,aquatic,freshwater,Animalia,Chordata,...,NaN,3.524021,NaN,NaN,0.000303,3.61,3.25,19.262070,NaN,1.659
28045,unpublished - Roussel,template,Roussel,-49.275057,70.114103,-49.275057 70.114103,aquatic,freshwater,Animalia,Chordata,...,NaN,3.538794,NaN,NaN,0.000287,3.61,3.25,19.262070,NaN,1.659
28046,unpublished - Roussel,template,Roussel,-49.275057,70.114103,-49.275057 70.114103,aquatic,freshwater,Animalia,Chordata,...,NaN,3.434890,NaN,NaN,0.000290,3.61,3.25,19.262070,NaN,1.659
28047,unpublished - Roussel,template,Roussel,-49.275057,70.114103,-49.275057 70.114103,aquatic,freshwater,Animalia,Chordata,...,NaN,3.443535,NaN,NaN,0.000312,3.61,3.25,19.262070,NaN,1.659
28048,unpublished - Roussel,template,Roussel,-49.275057,70.114103,-49.275057 70.114103,aquatic,freshwater,Animalia,Chordata,...,NaN,3.324923,NaN,NaN,0.000306,3.61,3.25,19.262070,NaN,1.659

In [28]:
# Look at the columns
StoichLife_df.columns

Index(['data.source1', 'data.type', 'data.provider1', 'lat.dec', 'long.dec',
       'location', 'habitat.gen', 'habitat', 'kingdom_init', 'phylum_init',
       'class_init', 'order_init', 'family_init', 'sp.morphosp_init',
       'kingdom_revised', 'phylum_revised', 'class_revised', 'order_revised',
       'family_revised', 'sp.morphosp_revised', 'species.level', 'autohetero',
       'invert.vert.auto', 'taxa.c', 'taxa.n', 'taxa.p', 'taxa.cn', 'taxa.cp',
       'taxa.np', 'taxa.mass.cn', 'taxa.mass.cp', 'taxa.mass.np',
       'body.weight.gr', 'temperature', 'radiation', 'N', 'P_ter', 'P_mar'],
      dtype='str')

In [42]:
# Specify the columns to keep
"""Only columns related to the species's species name and family name and nutrient data will be kept."""
columns_to_keep = [
'sp.morphosp_init', 'sp.morphosp_revised', 'family_init', 'taxa.c', 'taxa.n', 'taxa.p', 'taxa.cn', 'taxa.cp', 'taxa.np', 'taxa.mass.cn', 'taxa.mass.cp', 'taxa.mass.np', 
'body.weight.gr', 'temperature', 'radiation', 'N', 'P_ter', 'P_mar'
]

# Filter the dataset to keep only the necessary columns
StoichLife_filtered_df = StoichLife_df[columns_to_keep]

# Display the data
StoichLife_filtered_df

,sp.morphosp_init,sp.morphosp_revised,family_init,taxa.c,taxa.n,taxa.p,taxa.cn,taxa.cp,taxa.np,taxa.mass.cn,taxa.mass.cp,taxa.mass.np,body.weight.gr,temperature,radiation,N,P_ter,P_mar
0,Formicidae.sp11,Formicidae sp.11,Formicidae,NaN,11.510000,0.17,NaN,NaN,149.717942,NaN,NaN,67.705882,0.000628,7.46,6.20,60.439308,43.495975,0.782
1,Formicidae.sp9,Formicidae sp.9,Formicidae,41.800000,9.190000,0.37,5.304302,291.332886,54.923883,4.548422,112.972973,24.837838,0.000431,7.46,6.20,60.439308,43.495975,0.782
2,Atya.lanipes,Atya lanipes,Atyidae,48.440000,11.740000,0.94,4.811755,132.889673,27.617712,4.126065,51.531915,12.489362,0.199900,26.41,5.78,104.139830,18.790420,0.067
3,Xiphocaris.elongata,Xiphocaris elongata,Xiphocarididae,46.900000,11.460000,1.09,4.772608,110.958684,23.249069,4.092496,43.027523,10.513761,0.097500,26.41,5.78,104.139830,18.790420,0.067
4,Xiphocaris.elongata,Xiphocaris elongata,Xiphocarididae,45.960000,12.640000,1.09,4.240338,108.734779,25.642952,3.636076,42.165138,11.596330,0.109600,26.41,5.78,104.139830,21.631483,0.067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28044,Salvelinus fontinalis,Salvelinus fontinalis,Salmonidae,44.493203,12.625693,NaN,4.109661,NaN,NaN,3.524021,NaN,NaN,0.000303,3.61,3.25,19.262070,NaN,1.659
28045,Salvelinus fontinalis,Salvelinus fontinalis,Salmonidae,44.234026,12.499746,NaN,4.126889,NaN,NaN,3.538794,NaN,NaN,0.000287,3.61,3.25,19.262070,NaN,1.659
28046,Salvelinus fontinalis,Salvelinus fontinalis,Salmonidae,44.730870,13.022505,NaN,4.005717,NaN,NaN,3.434890,NaN,NaN,0.000290,3.61,3.25,19.262070,NaN,1.659
28047,Salvelinus fontinalis,Salvelinus fontinalis,Salmonidae,45.114385,13.101184,NaN,4.015799,NaN,NaN,3.443535,NaN,NaN,0.000312,3.61,3.25,19.262070,NaN,1.659
28048,Salvelinus fontinalis,Salvelinus fontinalis,Salmonidae,44.563635,13.402909,NaN,3.877475,NaN,NaN,3.324923,NaN,NaN,0.000306,3.61,3.25,19.262070,NaN,1.659

In [43]:
# Filter 'family_init' for a close relative of the dwarf white isopod
isopod_df = StoichLife_filtered_df[StoichLife_filtered_df['family_init'] == 'Platyarthridae']

# Display the result
isopod_df

,sp.morphosp_init,sp.morphosp_revised,family_init,taxa.c,taxa.n,taxa.p,taxa.cn,taxa.cp,taxa.np,taxa.mass.cn,taxa.mass.cp,taxa.mass.np,body.weight.gr,temperature,radiation,N,P_ter,P_mar
25347,"Platyarthrus Brandt, 1833",Platyarthrus sp.,Platyarthridae,NaN,1.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.07,3.7,1060.043928,66.802081,0.153

In [ ]:
# Filter 'sp.morphosp_revised' for Folsomia fimetaria

springtail_df = StoichLife_filtered_df[StoichLife_filtered_df['sp.morphosp_revised'] == 'Folsomia fimetaria']
                                       
# Display the results
springtail_df

,sp.morphosp_init,sp.morphosp_revised,family_init,taxa.c,taxa.n,taxa.p,taxa.cn,taxa.cp,taxa.np,taxa.mass.cn,taxa.mass.cp,taxa.mass.np,body.weight.gr,temperature,radiation,N,P_ter,P_mar
22490,"Desoria violacea (Tullberg, 1876)",Folsomia fimetaria,Isotomidae,39.13,9.561228,NaN,4.772695,NaN,NaN,4.092570,NaN,NaN,NaN,8.02,2.71,1626.260452,16.725162,0.475
22505,"Desoria violacea (Tullberg, 1876)",Folsomia fimetaria,Isotomidae,39.26,9.792730,NaN,4.675349,NaN,NaN,4.009097,NaN,NaN,NaN,8.02,2.71,1626.260452,16.725162,0.475